name: sme_customer_manager
description: Customer, inventory, and debt management app for small businesses.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  fl_chart: ^0.68.0
  path_provider: ^2.1.1
  http: ^1.2.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
